version: '3'
services:
  mysql:
    container_name: mysql
    image: mariadb
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=contact_admin_db
      - MYSQL_USER=sato1987
      - MYSQL_PASSWORD=sato1987
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
  phpmyadmin:
    container_name: phpMyAdmin
    depends_on:
      - mysql
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mysql
    restart: always
    ports:
      - "80:80"
  php:
    container_name: php-apache
    build: ./php
    volumes:
      - ./:/var/www/html
    ports:
      - 8080:80
    depends_on:
      - mysql
